primary_colors = c('gray' = '#737373',
	'red' = '#F15A60',
	'green' = '#7AC36A',
	'blue' = '#5A9BD4',
	'orange' = '#FBB879',
	'oldorange' = '#FAA75B',
	'purple' = '#9E67AB',
	'maroon' = '#470407',
	'oldmaroon' = '#CE7058',
	'magenta' = '#D77FB4')
category_colors = c('exact' = 'blue',
	'neighbor' = 'green',
	'distant' = 'red',
	'motif' = 'blue',
	'partialmotif' = 'green',
	'nomotif' = 'red',
	'bHLH' = 'orange',
	'ETS' = 'purple',
	'homeodomain' = 'maroon',
	'combined' = 'green',
	'experiment' = 'maroon',
	'control' = 'orange',
	'good' = 'green',
	'bad' = 'red')
category_names = c('exact' = 'Exact',
	'neighbor' = 'Neighbor',
	'distant' = 'Distant',
	'motif' = 'Motif',
	'partialmotif' = 'Partial Motif',
	'nomotif' = 'No Motif',
	'bHLH' = 'bHLH',
	'ETS' = 'ETS',
	'homeodomain' = 'homeodomain',
	'combined' = 'combined',
	'experiment' = 'Experiment',
	'control' = 'Control',
	'good' = 'good',
	'bad' = 'bad')
